name: Playwright Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    name: Run Playwright Tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        working-directory: ./RisilienceTest
        run: npm install

      - name: Install Playwright Browsers
        working-directory: ./RisilienceTest
        run: npx playwright install --with-deps

      - name: Run Playwright tests
        working-directory: ./RisilienceTest
        run: npx playwright test

      - name: Upload Playwright report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: playwright-report
          path: RisilienceTest/playwright-report/
